var vents = [
  "alto_sax",
// "bag_pipe",
//  "baritone_sax",
//  "bassoon",
//  "clarinet",
//  "english_horn",
//  "french_horn",
//  "fiddle",
  "flute",
//  "french_horn",
//  "harmonica",
//  "muted_trumpet",
  "oboe",
//  "ocarina",
//  "piccolo",
//  "tenor_sax",
//  "trombone",
//  "trumpet",
  "muted_trumpet",
//  "tuba"
]
